name: Test, Publish, Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup Node/NPM
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
      - name: Clean up
        run: npm run clean
      - name: Linting
        run: npm run lint:fix
      - name: Tests
        run: npm run test
      - name: Build
        run: npm run build
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Release
        uses: Roang-zero1/github-create-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
